save_dir:
  value: /storage/shared/mgh-hf-dataset/processed/ESD_09-01-23-1/
max_seq_len:
  min: 16
  max: 512
min_seq_len:
  min: 2
  max: 16
train_subset_size:
  value: FULL
train_subset_seed:
  value: 1
