defaults:
  - parameters: pretraining
  - _self_

entity: payal-collabs # ${oc.env:ENTITY}
project: EveryQueryGPT # ${oc.env:PROJECT_NAME}
program: scripts/pretrain.py
method: bayes
name: EST_sweep
metric:
  goal: minimize
  name: tuning_loss
early_terminate:
  type: hyperband
  min_iter: 1000
